### ISSUE TITLE
Emulate shutdowns are active by default when building

### ISSUE THREAD

**Issue by marcosilva85** [ppareit/Shutdown#2]
Emulate shutdowns should be 'false' by default so that when people build this application, the app is working (i.e., doing what is supposed to do).
If don't want to change to false, at least create a README.md on github stating that:
  emulate_shutdowns are 'true' by default, go to /res/values/bools.xml to change it to 'false'.

As stated in
  https://gitlab.com/fdroid/fdroiddata/issues/145

**Comment by ppareit** [comment]
Thanks Marco, this will be fixed in the next update. I will leave this open for now.

PS. When uploading an application to the f-droid store, contact me on pieter.pareit@gmail.com.
