### ISSUE TITLE
I haven't tried this app, and wonder what type of shutdown it does

### ISSUE THREAD

**Issue by unforgettableid** [ppareit/Shutdown#4]
I haven't tried this app yet.

1\.  Does this app do a full graceful shutdown?  Or does this app just sync and then do an abrupt, immediate poweroff?

A full graceful shutdown takes longer (perhaps 10 seconds instead of just 1 second) but is a much wiser choice.  A full graceful shutdown allows apps to take [certain important actions](http://android.stackexchange.com/questions/108674/why-does-adb-reboot-shut-down-my-phone-so-much-faster-than-usual-before-it-reb#130063) before the device powers off.

You don't have to be the app's maintainer to answer this question.  Anyone can answer by commenting below.

2\.  Dear Pieter:  Could you please edit the app's [Google Play Store description](https://play.google.com/store/apps/details?id=be.ppareit.shutdown&hl=en) to specify which kind of shutdown it does?

**Comment by ppareit** [comment]
(1) "sync; sleep 1; reboot -p", the sync should flush file buffers

I've think that before doing this, a loop that kill's all the processes might be even better. I should look into this.

(2) Yes, I will update the description, thanks for the notice!

I'll leave this as an open issue. Could be handy if some code change is made to improve the situation that this issue is referenced.

**Comment by unforgettableid** [comment]
Is it possible, on a rooted device, to trigger a full graceful shutdown which will do everything that Android's built-in "Shut down" button does?

**Comment by jeffkrebs** [comment]
If I'm reading this right, according to this information:
http://freaktab.com/forum/tv-player-support/general-tv-player-dicussions/3851-need-clean-shutdown-solution-for-all-corrupted-tv-sticks
https://stackoverflow.com/questions/9598522/android-root-poweroff
https://developer.android.com/reference/android/os/PowerManager.html

To perform a "nice" shutdown, an app needs to be system, not user.

Would it be possible for the app to contain two shutdown/reboot methods, and the app would determine the method by checking whether it resides in /system or /data ?

ROM developers (and TWRP users) would be able to put the app in /system/app.

**Comment by ppareit** [comment]
When the application has been build by an oem and is signed with the system keys, we now use the correct internal method.
If you are a ROM builder, contact me about this feature.

**Comment by unforgettableid** [comment]
Thank you!

After receiving an email notification of your most recent comment, I did more research and discovered that there probably exists a simpler way to trigger a graceful shutdown than @jeffkrebs suggested.  So I filed a new issue.

The new issue is #7 ("On all devices which support it, please do a graceful shutdown").
